
# Show the current folder in the prompt.
PS1='(ubuntu)\w $ '

# Allow aliases to work with sudo, i.e.: "sudo ll".
alias sudo='sudo '

# List the most recent files.
alias l='ls -ltr | tail -10'

alias ls='ls --color=auto'
alias ll='ls -l'
alias n='nimble'

# Use the manually built version of nim.
export PATH=/home/utf8tester/Nim/bin:$PATH

# Check for nim.
if ! command -v nim 2>&1 >/dev/null
then
  echo "You need to build nim. Here are the steps:"
  echo "cd ~/Nim"
  echo "./build_all.sh"
  echo "cd ~/utf8tests"
else
  cat /etc/os-release | head -1
  nim -v | head -1
fi

# Change ownership of the shared utf8test directory.
sudo chown utf8tester:utf8tester /home/utf8tester/utf8tests
